### ISSUE TITLE
Add Adblock Plus to firefox extension

### ISSUE THREAD

**Issue by FaustXVI** [nix-community/nur-combined#10]
@rycee, 

First of all, thank you for all the work you do. Every time I find something I love about nix, I see your name close by. <3

I use adblock plus which blocks ads very effectively and I didn't find a as good alternative so far.

Addon url : 

https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/

Thanks

**Comment by chayleaf** [comment]
do you not consider ublock origin a good alternative?

**Comment by Mic92** [comment]
Please report issues to individual nur repositories in their own repositories and not here.
