### ISSUE TITLE
hash mismatch in gamescope-3.11.32

### ISSUE THREAD

**Issue by Birdthatcantfly** [nix-community/nur-combined#7]
@dukzcry

error: hash mismatch in fixed-output derivation '/nix/store/0z74wpf8k3a44av6d7alw9d6rhw229kf-source.drv':

         specified: sha256-5VoNchJNopuwsWzC8InikeuMsjDuo6DdKDqG5WyWl3c=
         got: sha256-KMm/g6He1RjcXNa/9PlrfGdND4hurtMhX/7GvgwSnHs=

error: 1 dependencies of derivation '/nix/store/6wq9gaw049rchaf6c8cyf2hv9xg2wann-gamescope-3.11.32.drv' failed to build

**Comment by dukzcry** [comment]
Most likely due https://github.com/NixOS/nixpkgs/issues/179623

nixos-unstable build fails https://github.com/repos-holder/nur-packages/runs/7143726005?check_suite_focus=true
nixos-22.05 is fine https://github.com/repos-holder/nur-packages/runs/7143726106?check_suite_focus=true

**Comment by dukzcry** [comment]
@Birdthatcantfly  Should be fine now https://github.com/repos-holder/nur-packages/actions/runs/2600245396
Please update your nixos-unstable channel
